### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ishuar** [melvincv/10weeksofcloudops-w3#1]
Thank you @melvincv for taking this challenge and completing it. Great Job 👏 🌟 

Overall, the tasks have been successfully completed and are meeting expectations. However, there are a few areas where I believe improvements can be made. Please keep in mind that these are improvements that are mostly standard but do not mean the only way to go forward. Technically your project is pretty good and functional 👍 

If any of the below points is unclear or need more clarity please update the issue or directly contact me 😄 .

Let's get started. 🚀 

### Terraform Module 

- Avoid Static values in the modules, 

_"Try not to use fixed numbers or values inside the modules. Modules are designed to be reused, so it's better to use parameters that can be changed. Unless your organization has specific rules or ways of doing things that you want to follow, it's a good idea to make things flexible."_

For example:

From 
```hcl
resource "aws_vpc" "vpc" {
  cidr_block              = var.vpc_cidr
  instance_tenancy        = "default"
  enable_dns_hostnames    = true

  tags      = {
    Name    = "${var.project_name}-vpc"
  }
}
```
To

```hcl
resource "aws_vpc" "vpc" {
  cidr_block              = var.vpc_cidr
  instance_tenancy        = var.instance_tenancy
  enable_dns_hostnames    = var.enable_dns_hostnames

  tags      = merge(
  {
      Name    = "${var.project_name}-vpc"
    }, var.tags
  )
}
```
>> Respective variables need to be defined. Naming can be also flexible but that really subjective.

- Type casting and Descriptive Module variables 

_"In [variables.tf](https://github.com/melvincv/10weeksofcloudops-w3/blob/main/modules/vpc/variables.tf) variables should have respective types and descriptions for better usage of the module to someone who has not developed it."_

From:

```hcl
variable "vpc_cidr" {}

```

To

```hcl
variable "vpc_cidr" {
  type = string
  description = "The IPv4 CIDR block for the VPC"
}
```

>> The same can be followed with outputs in general.

- Missing terraform block in the module.

_"Terraform block enhances module control, consistency, and adaptability."_

Example: 
```hcl
terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
  }
}
```
> preferred in a new file `versions.tf` or `providers.tf` 

#### Security 🔒 

_"Protecting Your Secrets:  Sharing is great, but not when it comes to your passwords! 🙈 Uploading sensitive stuff like passwords to platforms like GitHub isn't the safest idea."_

Please take of this issue and use any secret management workflows. (Hint: GitHub Secrets in your GitHub action.) 

```hcl
# Create Aurora Cluster in the VPC
resource "aws_rds_cluster" "cloudops-w3-db" {
[....
  master_username           = "melvincv" ❌  ☠️ 
  master_password           = "Lh6KgnYHnGV34defo4G2mJjvtnCuJB" ❌ ☠️ 
...]
}
```
⚠️  This is a critical concern. ⚠️ 

### Good To Know and Intermediate Section.

- **IaC principle DRY: Do not repeat Yourself**

_"Usage of terraform `meta arguments`  [`for_each`](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each) or [`count`](https://developer.hashicorp.com/terraform/language/meta-arguments/count) to follow DRY."_

- **Usage of `working-directory` in your run steps.**

Refer to usage of [`working-directory`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun) in GitHub actions `run` step.

From
```yaml
# Initialize Terraform Providers
      - name: Initialize
        run: |
          cd cloudops-w3
          terraform init

      # Validates syntax
      - name: Validate
        run: |
          cd cloudops-w3
          terraform validate

      # Creates resources in AWS Cloud
      - name: Apply to AWS
        run: |
          cd cloudops-w3
          terraform apply --auto-approve
```
To
```yaml
      - name: Initialize and validate
        working-directory: cloudops-w3
        run: |
           terraform init
           terraform validate

      - name: apply
        working-directory: cloudops-w3
        run: terraform apply --auto-approve
```

>> There are a few more knits but I would like to keep them open for now.
